### PR TITLE
create .gitattributes

### PR DESCRIPTION
**Pull request by antonilol**
for the windows users among us (not me)

### CODE REVIEW

**Comment by Technici4n** [comment]
No clue what this does. I'm a windows user and I have not needed this.

**Comment by antonilol** [comment]
it tells git that `*.bat` files (gradlew.bat) have to end on CRLF and not LF.
some apps on windows (notepad.exe, but it has been fixed) do not see non-CRLF line endings and display the whole text on one line

**Comment by deirn** [comment]
Do people use notepad unironically? :sweat_smile: 

I don't see this PR is needed at all since you're not supposed to modify those files in the first place.

**Comment by antonilol** [comment]
> Do people use notepad unironically? sweat_smile

i did when i used windows more than a year ago :)

**Comment by modmuss50** [comment]
Sounds like this isnt needed. Thanks for the PR 👍

**Pull request closed without merging**
