### PR TITLE
Update Gradle version and Fabric dependencys

### PR DESCRIPTION
**Pull request by backryun**
Gradle 8.0 released, so I test example mod on Gradle 8.0
No build error, works fine on Minecraft.
And the mod targeted 1.19.3 so I updated Fabric dependencys(Loader,API,yarn).
I hope this commit intergrate on this project.

### CODE REVIEW

**Comment by RawDiamondMC** [comment]
It seems that gradle was updated to 8.0.1,will you update?

**Comment by backryun** [comment]
> It seems that gradle was updated to 8.0.1,will you update gradle to 8.0.1?

Of cource!

**Comment by RawDiamondMC** [comment]
> > It seems that gradle was updated to 8.0.1,will you update gradle to 8.0.1?
> 
> Of cource!

I saw that #222 use `gradlew wrapper --gradle-version=7.6` , maybe you need run `gradlew wrapper --gradle-version=8.0.1` to update?(maybe run this code will add more things?)

**Comment by modmuss50** [comment]
Hi, Thanks for this PR however its not quite right as it does not update the gradle wrapper, and the required loader version. To the recent report of[ supply chain attacks on the Gradle wrapper](https://blog.gradle.org/wrapper-attack-report) I have gone ahread and updated this myself.

See: https://github.com/FabricMC/fabric-example-mod/compare/86fc994be16b...3bf9aa7f113f

Thanks again for the PR 👍

**Pull request closed without merging**
