### PR TITLE
Slurp mod version from json to avoid issues in IDE

### PR DESCRIPTION
**Pull request by liach**
See FabricMC/fabric-loader#457

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by dexman545** [comment]
I don't think this is suitable for the example mod - other mod properties are set in gradle.properties, it shouldn't be inverted for this one special thing. If auto-run of processResources is really so generally needed, then adding things like Idea's extension so that processResources being autorun will already be configured, or a possible loom change to make it so.

**Comment by jackassmc** [comment]
Some properties are set in `gradle.properties` others are set in `fabric.mod.json`. When using the example mod you'll end up editing both of these files eventually.

**Comment by liach** [comment]
For @dexman545, I don't think it's quite easy to set the run configurations' resource classpath to the output of processresources. If we can add a correct dependency on process resources for loom, it's good too, but doing it correctly is a bit hard.

**Comment by dexman545** [comment]
I'm not sure about what loom can do, but it is worth mentioning as a possibility.

Yes,  you modify both files - that does not change the fact that `gradle.properties` is the correct place for mod version to be set. Few people need this functionality that while it would be good to have, it should be a background thing in loom, not a reworking of the example mod.

**Comment by sfPlayer1** [comment]
I don't buy into this gradle.properties argument, it obviously breaks in-dev use and alters the product in ways that are too extensive for a build system - a version is no build ID. Neither does it make a different to edit one file or another, having to change both is rare.

Running gradle in the IDE is not a solution, it turns instant run (esp. Eclipse) into waiting for gradle to start+finish and complicates the project setup.

**Comment by jackassmc** [comment]
Is this blocked until the loader version override is available or can this be merged already?

**Review by halotroop2288 — APPROVED** [review]

**Comment by modmuss50** [comment]
I added a thing to loom to do this nicely: https://github.com/FabricMC/fabric-loom/commit/2c464cdef372e92ea719eec618ae713d54cede89 Will need to wait for a stable build of 0.10

**Comment by halotroop2288** [comment]
> I added a thing to loom to do this nicely
> Will need to wait for a stable build of 0.10

What about 0.7?

**Comment by modmuss50** [comment]
> What about 0.7?

What do you mean? 0.10 is the version that is being developed atm and will be made stable once its ready. 0.7 was completed long ago.

**Comment by halotroop2288** [comment]
> 0.7 was completed long ago.

So this feature is already in 0.7 for those of us who still use Java 8 versions?

**Comment by modmuss50** [comment]
I should update the site, 0.9 is recommended for everyone, you can still use it build mods for java 8 (see fabric API's 1.16 branch)

**Comment by liach** [comment]
This is already fixed by loom, right?

**Pull request closed without merging**
