### PR TITLE
Update urls in gradle.properties

### PR DESCRIPTION
**Pull request by Earthcomputer**

### CODE REVIEW

**Comment by gudenau** [comment]
My main thought with this is it being a non-fabric site. Does anyone have any issues with that other than me?

**Comment by liach** [comment]
well fabric is owned and hosted by modmuss. at least so for maven.fabricmc.net (an alias for maven.modmuss50.me)

**Comment by gudenau** [comment]
So this could probably be turned into a cname on Fabric and have a virtual server handle it. Pretty sure Apache and nginx both support that.

**Review by gdude2002 — APPROVED** [review]

**Comment by gdude2002** [comment]
Has this really been open for 3 months? Let's get on with it.

Also @Earthcomputer you need to merge in/rebase the changes to `gradle.properties`

**Review by YTG1234 — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]

**Review by gdude2002 — APPROVED** [review]

**Review by HeyItsMeNobody — APPROVED** [review]

**Review by NinjaPhenix — APPROVED** [review]

**Pull request closed without merging**
