### PR TITLE
Appropriately deal with line endings in scripts

### PR DESCRIPTION
**Pull request by sydist**

### CODE REVIEW

**Comment by modmuss50** [comment]
This repo is automatically generated from https://github.com/FabricMC/fabricmc.net/tree/main/scripts/src/lib/template/templates the change should be made there. I wonder if its also worth having it as:

```
* text=auto eol=lf
*.bat text eol=crlf
```

So all text files are lf? other than the .bat file?

**Comment by sydist** [comment]
I see where you're coming from, but I don't think source files should be involved as the conversion is already handled by default in the newer versions of Git using core.autocrlf.
The default `gradle init` does this too, so I think it should be sufficient.

**Comment by sydist** [comment]
I'll move this to fabricmc/fabricmc.net

**Comment by sydist** [comment]
https://github.com/FabricMC/fabricmc.net/pull/74

**Pull request closed without merging**
