### PR TITLE
Update yarn, loader and api

### PR DESCRIPTION
**Pull request by 13rac1**
Significant version bumps since August. I figure this should be updated.

### CODE REVIEW

**Comment by liach** [comment]
Uh, we actually have a toolchain update and this pr may need to adjust accordingly.

**Comment by 13rac1** [comment]
Oh? This configuration builds and runs as-is. Perhaps no other updates are needed yet?
```
$ ./gradlew build

> Configure project :
Fabric Loom: 0.2.5-SNAPSHOT Build(jenkins #21)
:setting up loom dependencies
:setting up mappings (yarn 1.14.4+build.14)
:providing net.fabricmc.fabric-api:fabric-api:0.4.1+build.245-1.14 (net.fabricmc.yarn.1_14_4.14)
:remapping fabric-api-0.4.1+build.245-1.14.jar (TinyRemapper, intermediary -> named)
<snip>
:providing net.fabricmc:fabric-loader:0.6.4+build.169 (net.fabricmc.yarn.1_14_4.14)
:remapping fabric-loader-0.6.4+build.169.jar (TinyRemapper, intermediary -> named)
sources
:loading intermediary -> named source mappings
<snip>
> Task :compileJava
:setting java compiler args
Could not find refmap definition, will be using default name: fabric-example-mod-refmap.json
Note: SpongePowered MIXIN Annotation Processor Version=0.7.11
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
<snip>

> Task :remapJar
:remapping fabric-example-mod-1.0.0-dev.jar
mixin-map-1.14.4-14.tiny: 4976 classes, 21969 methods, 18195 fields

> Task :remapSourcesJar
:loading named -> intermediary source mappings
:remapping source jar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 32s
6 actionable tasks: 4 executed, 2 up-to-date
```

**Comment by natanfudge** [comment]
Modmuss backported the parser fix to 0.2.5 so this should be ok

**Comment by liach** [comment]
We should just use v2 mappings in the example mod, so need an update to build.gradle

**Comment by 13rac1** [comment]
I'm not 100% on what you'd like me to change. Do you mean the loom version?

```diff
diff --git a/build.gradle b/build.gradle
index 8542e88..46a0735 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,5 +1,5 @@
 plugins {
-       id 'fabric-loom' version '0.2.5-SNAPSHOT'
+       id 'fabric-loom' version '0.2.6-SNAPSHOT'
        id 'maven-publish'
 }
```

On my Ubuntu 18.04:
```bash
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

**0.2.5** - Works fine.
```
[11:21:20] [main/INFO]: LWJGL Version: 3.2.2 build 10
```

**0.2.6** - Crashes `Failed to locate library: liblwjgl.so`:
```
[11:22:14] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
<snip>
```

**Comment by modmuss50** [comment]
Humm, 0.2.6 should work just fine? What IDE are you using to run the game? if its vscode or eclipse you need to re-run the setup tasks. For now its still classed as experimetal and there will be a full upgrade guide covering this once im sure its stable enough to be used by the masses.

I did plan on doing the full update to v2 mappings in one commit to this repo to show users how to do it along with the versions.

**Comment by 13rac1** [comment]
I use vscode, but this runtime failure occurs IDE-less in the CLI. I've recloned, changed the `5` to `6`, run the build/client, and gotten the same issue multiple times:
```bash
$ git clone https://github.com/13rac1/fabric-example-mod.git
$ cd fabric-example-mod
$ git checkout bump-deps
$ vi build.gradle
$ ./gradlew runClient
```
Crash log: [crash-2019-11-14_11.42.01-client.txt](https://github.com/FabricMC/fabric-example-mod/files/3848377/crash-2019-11-14_11.42.01-client.txt)

I've reproduced within Docker. The `runClient` task crashes with the same error conveniently before attempting to open a Window.
```
docker run -it --rm openjdk:11-stretch bash
```

I was hoping to just bump the other versions in this PR. Seems best to hold off on the v2 mappings for now? Feel free to just close this PR if you want to handle it later. Thanks!

**Comment by modmuss50** [comment]
What are the contents of `<project-dir>/.gradle/loom-cache/launch.cfg`? after running the runClient command?

**Comment by 13rac1** [comment]
```bash
$ cat .gradle/loom-cache/launch.cfg
commonProperties
        fabric.development=true
clientArgs
        --assetIndex
        1.14.4-1.14
        --assetsDir
        /root/.gradle/caches/fabric-loom/assets
clientProperties
        java.library.path=/root/.gradle/caches/fabric-loom/natives/1.14.4
        org.lwjgl.librarypath=/root/.gradle/caches/fabric-loom/natives/1.14.4
```

Complete log of a run within Docker: [docker-openjdk11-fabric-loom-0.2.6.log](https://github.com/FabricMC/fabric-example-mod/files/3848827/docker-openjdk11-fabric-loom-0.2.6.log) Steps to reproduce:

```bash
docker run -it --rm openjdk:11-stretch bash
git clone https://github.com/13rac1/fabric-example-mod.git
cd fabric-example-mod
git checkout bump-deps-loom-0.2.6
./gradlew runClient
```

**Comment by modmuss50** [comment]
Humm yeah, reproduced in docker. Need to fix this before 0.2.6 becomes the main version.

**Comment by modmuss50** [comment]
And can reproduce on MacOS

**Comment by modmuss50** [comment]
Can you try again now please? Seems to have fixed it on mac os

**Comment by 13rac1** [comment]
Works!

It's working in Docker (AKA crashing as expected) with the new snapshot. Was `Fabric Loom: 0.2.6-SNAPSHOT Build(jenkins #19)`, now `Fabric Loom: 0.2.6-SNAPSHOT Build(jenkins #20)`. Locally, I had to manually remove the loom jars, since these snapshots don't have version numbers. Used `find ~/.gradle/ -name "*fabric-loom*" | xargs rm -rf` because I didn't want to clear my entire gradle cache. Should/can Loom build versions be added?

**Comment by liach** [comment]
please include the build.gradle loom change since loom 0.2.6 works. also another part of build.gradle will need an update

**Comment by natanfudge** [comment]
I would rather know https://github.com/FabricMC/fabric-loom/pull/141 and https://github.com/FabricMC/fabric-loom/pull/145 are OK first.

**Comment by 13rac1** [comment]
@liach :laughing: I forgot the `git add`, before the amend. Fixed.

**Comment by modmuss50** [comment]
There is a new loader update, and move to v2 mappings then im happy with this.

**Comment by 13rac1** [comment]
I've updated to the versions listed on https://modmuss50.me/fabric.html?&version=1.14.4 `runClient` works as expected. I'm not sure this means I've set the "v2 mappings" though, because I cannot find documentation explaining the difference and internet searches lead me back to this PR. :laughing:

**Comment by modmuss50** [comment]
Pushed V2 and a small tweak to the mod.json to your fork. 

This should be good to be merged now.

**Comment by natanfudge** [comment]
@13rac1, the best way to stay up to date is joining the discord https://discord.gg/v6v4pMv

**Comment by 13rac1** [comment]
@natanfudge Ah ha! Thanks! We need to post elsewhere too, since information on Discord will not necessarily be available in the future. Should the _Fabric Latest Versions_ website be updated too?

**Comment by modmuss50** [comment]
Yes, I need to do that.

**Pull request merged**
