### PR TITLE
Prepend mixins. to mixin config file names

### PR DESCRIPTION
**Pull request by JamiesWhiteShirt**
This should be a useful default since prefixing the file name with `mixins.` enables class autocompletion and checking when using the MCDev plugin. In addition it makes it clear that they are mixin configs.

### CODE REVIEW

**Comment by Prospector** [comment]
I'm pretty sure you actually need the prefix, "mixins.", no?

**Comment by strikerrocker** [comment]
Nope its not

**Comment by JamiesWhiteShirt** [comment]
You're right, it's `mixins.`. I stated it incorrectly in the PR description and commit message but the code is correct.

**Comment by asiekierka** [comment]
I prefer the mixin.json suffix as it fits our existing mod.json suffix.

**Comment by Prospector** [comment]
Maybe PR the Minecraft Development plugin then

**Comment by JamiesWhiteShirt** [comment]
Relevant code is here: https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/kotlin/com/demonwav/mcdev/platform/mixin/config/MixinConfigFileTypeFactory.kt#L24

[The existing implementation is based on a convention that is used in most projects.](https://github.com/minecraft-dev/MinecraftDev/pull/188)

Would you propose `endsWith("mixins.json")` as an alternative?

**Comment by LumberWizard** [comment]
I personally like *.mixins.json better.

**Comment by ehwuts** [comment]
I prefer mixin.foo.json for sorting implications and for the conceptual ordering: It's a mixin for foo in the format json.

Plus it matches all my lang files being named lang.foo.json

**Comment by MasterEric** [comment]
I use `modid.mixin.json` since `*.mod.json` is the extension for mods and `*.mixin.json` is the extension for mixins.

**Comment by Boundarybreaker** [comment]
I'm gonna go with suffix myself, since Fabric is all suffix-y.

**Comment by Lordmau5** [comment]
> I prefer mixin.foo.json for sorting implications and for the conceptual ordering: It's a mixin for foo in the format json.
> 
> Plus it matches all my lang files being named lang.foo.json

This seems like the most logical approach to me, too, when it comes to easily seeing what something is about.

If this would get in, I would assume the naming convention for mods should also be changed to `mod.*.json` to fit this.

**Comment by Ansraer** [comment]
> I prefer mixin.foo.json for sorting implications and for the conceptual ordering: It's a mixin for foo in the format json.
> 
Agreed

**Comment by valoeghese** [comment]
> I'm gonna go with suffix myself, since Fabric is all suffix-y.

Except in mappings lol.

**Comment by Prospector** [comment]
If you want the minecraft dev plugin support, you need the `mixins.` prefix

**Comment by InsomniaKitten** [comment]
I agree that this change should be made in the example mod, to accommodate for how the IDE plugin currently functions, which in turn will be helpful to new users (the target user base of this repository).

**Comment by Codetoil** [comment]
Will this pr be closed?

**Comment by Prospector** [comment]
It was never implemented, so I don't think so

**Comment by DemonWav** [comment]
This isn't necessary anymore (not like it was ever going to be merged anyways): https://github.com/minecraft-dev/MinecraftDev/commit/12d7b0cf94f9a71d56e329b61c96d2ad526a6803

**Comment by modmuss50** [comment]
Thanks for that, I will close this PR now, as I dont see it going anywhere and its no longer needed.

**Pull request closed without merging**
