### PR TITLE
Add a clientside mod

### PR DESCRIPTION
**Pull request by rizet**

### CODE REVIEW

**Review by modmuss50 — CHANGES_REQUESTED** [review]
This is quite dangerous. I would HIGHLY recommend creating a seprate class for client side code.

**Review by OroArmor — CHANGES_REQUESTED** [review]
Don't merge the client and general initialization into one class. This will cause more issues than helping people

**Comment by frqnny** [comment]
Lol very bad idea. If you have a client sided field like an entity layer it would immediately crash on server start up

**Comment by rizet** [comment]
I made the appropriate changes you requested.

**Comment by rizet** [comment]
When is this PR going to be reviewed again? It's been four days.

**Review by frqnny — APPROVED** [review]
I think it’s good enough.

**Review by StoneLabs — APPROVED** [review]

**Comment by rizet** [comment]
@modmuss50 it's been a month. Would you like to review again?

**Comment by rizet** [comment]
my g this is kinda dead now i'll just close it

**Pull request closed without merging**
