### PR TITLE
loader 0.12.8, right?

### PR DESCRIPTION
**Pull request by antonilol**

### CODE REVIEW

**Comment by modmuss50** [comment]
This breaks the example mod... as it doesnt even run with 0.12.8

**Comment by antonilol** [comment]
if i clone my `patch-4` it just works (with `./gradlew runClient` and normal minecraft)

**Comment by antonilol** [comment]
and [this page](https://fabricmc.net/versions.html?&version=1.18) tells me for minecraft 1.18 you have to use loader 0.12.8

**Comment by modmuss50** [comment]
It works now you updated loader 👍

**Comment by antonilol** [comment]
yeah saw the problem

**Pull request closed without merging**
